# Generated by Django 4.2 on 2023-05-09 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_question_question_type_alter_option_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="total_answer",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=122)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="api.question",
                    ),
                ),
            ],
        ),
    ]
