# Generated by Django 4.2 on 2023-05-09 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_question_total_answer_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
    ]
