# Generated by Django 4.2 on 2023-05-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_currentanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="isCompleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="currentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_answer",
                to="api.question",
            ),
        ),
    ]
