# Generated by Django 4.2 on 2023-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_quiz_iscompleted_alter_currentanswer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="isAttempted",
            field=models.BooleanField(default=False),
        ),
    ]
