# Generated by Django 4.2 on 2023-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_question_isattempted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="isAttempted",
        ),
        migrations.AddField(
            model_name="quiz",
            name="total_marks",
            field=models.IntegerField(default=0),
        ),
    ]
